/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jay Aguirre Alfeche
 */

public class TuitionFeeCalculator extends javax.swing.JFrame {
        
        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TuitionFeeCalculator.class.getName());

        /**
         * Creates new form TuitionFeeCalculator
         */
        public TuitionFeeCalculator() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblAdd = new javax.swing.JComboBox<>();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                lblAdd2 = new javax.swing.JComboBox<>();
                jLabel3 = new javax.swing.JLabel();
                txtOutput = new javax.swing.JTextField();
                btnMultiply = new javax.swing.JButton();
                txtOutput2 = new javax.swing.JLabel();
                lblOutput = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                lblAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSCS", "BSIS" }));
                lblAdd.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                lblAddItemStateChanged(evt);
                        }
                });
                lblAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lblAddActionPerformed(evt);
                        }
                });

                jLabel1.setText("Student Course");

                jLabel2.setText("Student Type");

                lblAdd2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Scholar", "Working Student" }));
                lblAdd2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lblAdd2ActionPerformed(evt);
                        }
                });

                jLabel3.setText("Units");

                btnMultiply.setText("Compute Tuition");
                btnMultiply.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMultiplyActionPerformed(evt);
                        }
                });

                txtOutput2.setText("Result wil be displayed below:");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(15, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMultiply)
                                .addGap(18, 18, 18)
                                .addComponent(txtOutput2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
                // TODO add your handling code here:

                try {

                        double units = Double.parseDouble(txtOutput.getText());
                        double ratePerUnit = 0;
                        double discount = 0;

                        String course = lblAdd.getSelectedItem().toString();
                        if (course.equals("bsit")) {
                                ratePerUnit = 1500;
                        } else if (course.equals("bscs")) {
                                ratePerUnit = 1000;
                        } else if (course.equals("bsis")) {
                                ratePerUnit = 1400;
                        }

                        String type = lblAdd2.getSelectedItem().toString();
                        if (type.equals("scholar")) {
                                discount = 0.50;
                        } else if (type.equals("working student")) {
                                discount = 0.20;
                        } else {
                                discount = 0;
                        }

                        double totalTuition = units * ratePerUnit;
                        double finalPrice = totalTuition - (totalTuition * discount);
                        double compute = 1500 * 0.50;

                        String result = "--- Tuition calculation ---n"
                                + "Course: " + course.toUpperCase() + "n"
                                + "Total Units: " + units + "n"
                                + "Type: " + type + "n"
                                + "ratePerUnit: " + totalTuition + "n"
                                + "Discount: " + (discount * 100 + compute) 
                                + "PHP: " + (ratePerUnit) + "%n"
                                + "final tuition fee: " + finalPrice;
                       
                } catch (NumberFormatException e) {
                        lblOutput.setText("Error: Please enter a valid number for units!");
                }
        

        }//GEN-LAST:event_btnMultiplyActionPerformed

        private void lblAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAddActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_lblAddActionPerformed

        private void lblAddItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lblAddItemStateChanged
                // TODO add your handling code here:
        }//GEN-LAST:event_lblAddItemStateChanged

        private void lblAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAdd2ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_lblAdd2ActionPerformed
         public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                break;
                        }
                }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                        java.awt.EventQueue.invokeLater(() -> new TuitionFeeCalculator().setVisible(true));

        /* Create and display the form */
}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnMultiply;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JComboBox<String> lblAdd;
        private javax.swing.JComboBox<String> lblAdd2;
        private javax.swing.JTextField lblOutput;
        private javax.swing.JTextField txtOutput;
        private javax.swing.JLabel txtOutput2;
        // End of variables declaration//GEN-END:variables
}
